name: curator
description: A library management system.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  flutter_acrylic: ^1.1.3
  

  msix: ^3.16.6
  # flutter_gen: ^5.3.2
  flutter_svg: ^2.0.9
  intl: ^0.18.1
  flutter_riverpod: ^2.4.6
  fluttericon: ^2.0.0
  responsive_sizer: ^3.2.0
  fl_chart: ^0.64.0
  percent_indicator: ^4.2.3
  mysql1: ^0.20.0
  flutter_barcode_scanner: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# flutter_gen:
#   output: lib/gen/ # Optional (default: lib/gen/)
#   line_length: 80 # Optional (default: 80)

#   # Optional
#   integrations:
#     flutter_svg: true
#     flare_flutter: true
#     rive: true
#     lottie: true

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/images/
    - assets/fonts/
    - assets/svgs/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/POPPINS-REGULAR.TTF
        - asset: assets/fonts/POPPINS-MEDIUM.TTF
          weight: 500
        - asset: assets/fonts/POPPINS-SEMIBOLD.TTF
          weight: 700
